import type { TestCase } from "@/api/types";

function download(filename: string, text: string, mime: string): void {
  const blob = new Blob([text], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

const xmlEscape = (s: string) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

/** Machine-readable test-case manifest (XML). */
export function downloadTestCasesXml(tests: TestCase[], stem: string): void {
  const rows = tests
    .map((t) => {
      const attrs = [
        `id="${xmlEscape(t.test_id)}"`,
        `category="${xmlEscape(t.category ?? "")}"`,
        `technique="${xmlEscape(t.technique ?? "")}"`,
        `method="${xmlEscape(t.method ?? "")}"`,
        `path="${xmlEscape(t.path ?? "")}"`,
        `expected_status="${t.expected_status_code ?? ""}"`,
        `adversarial="${Boolean(t.adversarial)}"`,
      ].join(" ");
      const input = t.input_data ? xmlEscape(JSON.stringify(t.input_data)) : "";
      return `  <testcase ${attrs}>\n    <title>${xmlEscape(t.title ?? "")}</title>\n    <input>${input}</input>\n  </testcase>`;
    })
    .join("\n");
  const xml = `<?xml version="1.0" encoding="UTF-8"?>\n<testsuite name="sentinel-qa" tests="${tests.length}">\n${rows}\n</testsuite>\n`;
  download(`${stem}.xml`, xml, "application/xml");
}

/** Raw test cases (JSON) for tooling / re-import. */
export function downloadTestCasesJson(tests: TestCase[], stem: string): void {
  download(`${stem}.json`, JSON.stringify(tests, null, 2), "application/json");
}

/**
 * Runnable JS scaffold (Node 18+ fetch) that exercises each test case against
 * SENTINEL_BASE_URL and asserts the expected status. Honest scope: this is a
 * functional HTTP scaffold generated from the bound method/path/expected — it
 * does not replicate the full pytest harness (auth bootstrap, repeat loops,
 * forbidden-content tiers). The .py file remains the production runner.
 */
export function downloadJsScript(tests: TestCase[], stem: string): void {
  const cases = tests.map((t) => ({
    id: t.test_id,
    method: (t.method ?? "GET").toUpperCase(),
    path: t.path ?? "/",
    expected: t.expected_status_code ?? null,
    body: t.adversarial ? null : t.input_data ?? null,
  }));
  const js = `// Generated by Sentinel-QA — runnable JS scaffold (Node 18+).
// Functional HTTP checks only; see test_sentinel_api_generated.py for the
// full harness (auth, repeat loops, forbidden-content assertions).
const BASE_URL = process.env.SENTINEL_BASE_URL || "http://localhost:8000";
const TOKEN = process.env.SENTINEL_TEST_BEARER_TOKEN || "";
const CASES = ${JSON.stringify(cases, null, 2)};

let passed = 0, failed = 0;
for (const c of CASES) {
  try {
    const headers = { "Content-Type": "application/json" };
    if (TOKEN) headers["Authorization"] = "Bearer " + TOKEN;
    const init = { method: c.method, headers };
    if (c.body && c.method !== "GET") init.body = JSON.stringify(c.body);
    const res = await fetch(BASE_URL + c.path, init);
    const ok = c.expected == null || res.status === c.expected;
    console.log((ok ? "PASS" : "FAIL") + " " + c.id + " -> " + res.status +
      (c.expected != null ? " (expected " + c.expected + ")" : ""));
    ok ? passed++ : failed++;
  } catch (e) {
    console.log("ERROR " + c.id + " -> " + e.message);
    failed++;
  }
}
console.log("\\n" + passed + " passed, " + failed + " failed of " + CASES.length);
process.exit(failed > 0 ? 1 : 0);
`;
  download(`${stem}.mjs`, js, "text/javascript");
}
